version: 2.1

defaults: &defaults
  docker:
    - image: circleci/python:3.7.2
  working_directory: ~/project


prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip3 install --upgrade pip


jobs:
  test_deployment_pima:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv
      - run:
          name: Install requirements
          command: |
            source venv/bin/activate
            pip3 install -r pima_package/deployment_pima/requirements.txt
      - run:
          name: Train model
          command: |
            source venv/bin/activate
            python3 pima_package/deployment_pima/deployment_pima/train_pipeline.py
      - run:
          name: Running model tests
          command: |
            source venv/bin/activate
            py.test -vv pima_package/deployment_pima/tests

  test_pima_api:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - py-deps-{{ checksum "pima_package/pima_api/requirements.txt" }}
      - *prepare_venv
      - run:
          name: Running api tests
          command: |
            pip3 install -r pima_package/pima_api/requirements.txt
            py.test -vv pima_package/pima_api/tests
      - save_cache:
          key: py-deps-{{ checksum "pima_package/pima_api/requirements.txt" }}
          paths:
            - "/venv"

  train_and_upload_model:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv
      - run:
          name: Install requirements
          command: |
            source venv/bin/activate
            pip3 install -r pima_package/deployment_pima/requirements.txt
      - run:
          name: Train model
          command: |
            source venv/bin/activate
            PYTHONPATH=./pima_package/deployment_pima python3 pima_package/deployment_pima/deployment_pima/train_pipeline.py
      - run:
          name: Publish model to Gemfury
          command: |
            source venv/bin/activate
            chmod +x ./scripts/publish_model.sh
            ./scripts/publish_model.sh ./pima_package/deployment_model/


workflows:
  version: 2.1
  test-all:
    jobs:
      - test_deployment_pima
      - train_and_upload_model:
          requires:
            - test_deployment_pima
      - test_pima_api:
          requires:
            - test_deployment_pima
            - train_and_upload_model
